name: gingersnappish
favicon: null
layout_spectrum: 0.33404562110081315
typography_spectrum: 0.20172444405034184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080500'
    - '#3e3013'
    - '#7b6732'
    - '#fae3c1'
    - '#9f853c'
  brandStrength: 0.125
  lightness: 0.9604915420059115
  saturation: 0.8864912607241422
  rhythmicContrast: 0.09715776890516281
purpose: []
